language: minimal

services:
  - docker
 
before_install:
  - docker build -t docker-dynamic-dns .

script:
  - EXT_IP=$(curl -s http://myexternalip.com/raw)
  - echo $EXT_IP
  - docker run -it --rm --name=no-ip1 -e USER=docker-dynamic-dns -e IP=$EXT_IP -e HOSTNAME=docker-dynamic-dns.dns04.com,docker-dynamic-dns.dns05.com -e DETECTIP=0 -e PASSWORD='R)6\W\KM$jj*Z_B!' docker-dynamic-dns
  - DNS1_IP=$(dig +short docker-dynamic-dns.dns04.com)
  - echo $DNS1_IP
  - DNS2_IP=$(dig +short docker-dynamic-dns.dns05.com)
  - echo $DNS2_IP
  - [ "$DNS1_IP" = "$EXT_IP" ]
  - [ "$DNS2_IP" = "$EXT_IP" ]

